/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OdsSelectorWidget {
        /**
          * The project name displayed in the widget header.
          * @type {string}
          * @memberof OdsSelectorWidget
          * @example project = 'PROJECT 1';
          * @default 'PROJECT 1'
         */
        "project": string;
        /**
          * The service URL to fetch platform data from. Use ${project} as a placeholder that will be replaced with the project name.
          * @type {string}
          * @memberof OdsSelectorWidget
          * @example serviceUrl = 'https://api.example.com/platforms/${project}';
         */
        "serviceUrl": string;
    }
}
declare global {
    interface HTMLOdsSelectorWidgetElement extends Components.OdsSelectorWidget, HTMLStencilElement {
    }
    var HTMLOdsSelectorWidgetElement: {
        prototype: HTMLOdsSelectorWidgetElement;
        new (): HTMLOdsSelectorWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "ods-selector-widget": HTMLOdsSelectorWidgetElement;
    }
}
declare namespace LocalJSX {
    interface OdsSelectorWidget {
        /**
          * The project name displayed in the widget header.
          * @type {string}
          * @memberof OdsSelectorWidget
          * @example project = 'PROJECT 1';
          * @default 'PROJECT 1'
         */
        "project"?: string;
        /**
          * The service URL to fetch platform data from. Use ${project} as a placeholder that will be replaced with the project name.
          * @type {string}
          * @memberof OdsSelectorWidget
          * @example serviceUrl = 'https://api.example.com/platforms/${project}';
         */
        "serviceUrl"?: string;
    }
    interface IntrinsicElements {
        "ods-selector-widget": OdsSelectorWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ods-selector-widget": LocalJSX.OdsSelectorWidget & JSXBase.HTMLAttributes<HTMLOdsSelectorWidgetElement>;
        }
    }
}
